root: true
extends: availity/browser
env:
  jest: true
rules:
  react/destructuring-assignment: 0
  react/forbid-foreign-prop-types: 0
  react/no-access-state-in-setstate: 0
  guard-for-in: 0
  no-restricted-syntax: 0
  react/prefer-stateless-function: 0
  unicorn/no-reduce: 0
  # disabled to support older versions of workflow that do not polyfill Array.prototype.find (not supported in IE)
  unicorn/prefer-array-find: 0
  unicorn/no-abusive-eslint-disable: 0
  unicorn/no-lonely-if: 0
  unicorn/no-array-for-each: 0
