[build]
  publish = "docusaurus/build"
  command = "yarn run build:docs"

[build.environment]
  NODE_VERSION = "14"


[[redirects]]
  from = "/availity-react" # docusaurus baseUrl
  to = "/"
  force = true # ensure redirect