[build]
  publish = "docusaurus/build"
  command = "yarn run build:docs"

[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.19.1"

[[redirects]]
  from = "/availity-react/*" # docusaurus baseUrl
  to = "/:splat"
  force = true # ensure redirect
  status = 200 # changes redirect to rewrite, keeps baseUrl for docusaurus but serves / from netlify

[build.processing.html]
  pretty_urls = false # https://v2.docusaurus.io/docs/deployment/#deploying-to-netlify
