# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Release

on:
  push:
    branches: [master]

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: dependency-cache-${{ hashFiles('./yarn.lock') }}
          restore-keys: dependency-cache-${{ hashFiles('./yarn.lock') }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test:ci
      - uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - run: git config --global user.email ${{ secrets.GH_EMAIL }}
      - run: git config --global user.name ${{ secrets.GH_USER }}
      - run: yarn release:ci
      - run: yarn deploy:ci
